export const categoryMapping = {
  'Daily expenses and consumption': 'A',
  'Financial management and transfers': 'B',
  'Housing and facilities': 'C',
  'Income and investments': 'D',
  'Insurance and Health': 'E',
  'Other miscellaneous': 'F'
};

export const subCategoryMapping = {
  'Groceries': '1',
  'Entertainment': '2',
  'Amazon': '3',
  'Dine Out': '4',
  'Travel': '5',
  'Fitness': '6',
  'Food Shopping': '7',
  'Clothes': '8',
  'Savings': '1',
  'Bills': '2',
  'Cash': '3',
  'Account transfer': '4',
  'Home Improvement': '1',
  'Hotels': '2',
  'Services/Home Improvement': '3',
  'Mortgage': '4',
  'Rent': '5',
  'Investment': '1',
  'Supplementary Income': '2',
  'Travel Reimbursement': '3',
  'Safety Deposit Return': '4',
  'Interest': '5',
  'Paycheck': '6',
  'Purchase of uk.eg.org': '7',
  'Insurance': '1',
  'Health': '2',
  'Others': '1',
  'Null': '2',
  'Services': '3',
  'Other Shopping': '4'
};
